/**
 * Calendar 组件 - Vintage Nostalgia 复古怀旧风格
 */
export const calendarConfig = {
  slots: {
    root: [
      'p-3 font-serif',
      'rounded-[2px]',
      'border-2 border-border',
      'bg-surface-1',
      'shadow-[inset_0_1px_2px_rgba(44,24,16,0.1)]',
    ],
    months: 'flex flex-col sm:flex-row space-y-4 sm:space-x-4 sm:space-y-0',
    month: 'space-y-4',
    caption: 'flex justify-center pt-1 relative items-center',
    captionLabel: 'font-serif text-sm font-bold uppercase tracking-wide',
    nav: 'space-x-1 flex items-center',
    navButton: [
      'inline-flex items-center justify-center',
      'h-7 w-7',
      'rounded-[2px]',
      'border-2 border-border',
      'bg-transparent',
      'opacity-50',
      'transition-opacity duration-150',
      'hover:opacity-100',
    ],
    navButtonPrevious: '',
    navButtonNext: '',
    table: 'w-full border-collapse space-y-1',
    headRow: 'flex',
    headCell: 'text-muted-foreground rounded-[2px] w-9 font-mono font-normal text-[0.8rem] uppercase',
    row: 'flex w-full mt-2',
    cell: 'relative p-0 text-center font-mono text-sm focus-within:relative focus-within:z-20',
    day: [
      'inline-flex items-center justify-center',
      'h-9 w-9',
      'rounded-[2px]',
      'border-2 border-transparent',
      'font-mono font-normal',
      'transition-all duration-150',
      'hover:bg-surface-1 hover:border-border',
      'aria-selected:bg-primary aria-selected:text-primary-foreground aria-selected:border-[#5C4033]',
      'aria-selected:opacity-100',
    ],
    daySelected: [
      'bg-primary text-primary-foreground border-[#5C4033]',
      'shadow-[inset_0_-1px_0_0_rgba(92,64,51,0.3)]',
    ],
    dayToday: 'bg-surface-2 text-foreground border-border',
    dayOutside: 'text-muted-foreground opacity-50',
    dayDisabled: 'text-muted-foreground opacity-50',
    dayHidden: 'invisible',
  },
};
