import type { ThemeDefinition } from '@/types';
import { tokens, meta } from './tokens';
import { playgroundGlobalCss } from './styles';
import {
  buttonConfig,
  badgeConfig,
  inputConfig,
  textareaConfig,
  labelConfig,
  checkboxConfig,
  switchConfig,
  sliderConfig,
  toggleConfig,
  radioGroupConfig,
  radioGroupItemConfig,
  progressConfig,
  skeletonConfig,
  spinnerConfig,
  avatarConfig,
  avatarFallbackConfig,
  kbdConfig,
  separatorConfig,
  cardConfig,
  collapsibleConfig,
  aspectRatioConfig,
  scrollAreaConfig,
  scrollBarConfig,
  popoverConfig,
  tooltipConfig,
  tabsConfig,
  dropdownMenuConfig,
  alertConfig,
  alertDialogConfig,
  breadcrumbConfig,
  buttonGroupConfig,
  commandConfig,
  contextMenuConfig,
  drawerConfig,
  formConfig,
  hoverCardConfig,
  inputGroupConfig,
  inputOtpConfig,
  menubarConfig,
  paginationConfig,
  selectConfig,
  sheetConfig,
  tableConfig,
  toggleGroupConfig,
  calendarConfig,
  navigationMenuConfig,
  comboboxConfig,
  resizableConfig,
  datePickerConfig,
  carouselConfig,
  sonnerConfig,
  dataTableConfig,
  chartConfig,
  accordionConfig,
  dialogConfig,
  sidebarConfig,
} from './components';

/**
 * Cyberpunk Dark Theme
 *
 * Design Philosophy:
 * - Geometry: Chamfered edges (clip-path), no border-radius
 * - Texture: Neon glow, scanlines, glitch effects
 * - Typography: Monospace, uppercase, wide tracking
 */
export const cyberpunkDarkTheme: ThemeDefinition = {
  id: 'cyberpunk-dark',
  name: 'Cyberpunk Dark',
  nameKey: 'themeNameCyberpunkDark',

  isDark: meta.isDark,
  cssVars: tokens,

  components: {
    Button: buttonConfig,
    Badge: badgeConfig,
    Input: inputConfig,
    Textarea: textareaConfig,
    Label: labelConfig,
    Checkbox: checkboxConfig,
    Switch: switchConfig,
    Slider: sliderConfig,
    Toggle: toggleConfig,
    RadioGroup: radioGroupConfig,
    RadioGroupItem: radioGroupItemConfig,
    Progress: progressConfig,
    Skeleton: skeletonConfig,
    Spinner: spinnerConfig,
    Avatar: avatarConfig,
    AvatarFallback: avatarFallbackConfig,
    Kbd: kbdConfig,
    Separator: separatorConfig,
    Card: cardConfig,
    Collapsible: collapsibleConfig,
    AspectRatio: aspectRatioConfig,
    ScrollArea: scrollAreaConfig,
    ScrollBar: scrollBarConfig,
    Popover: popoverConfig,
    Tooltip: tooltipConfig,
    Tabs: tabsConfig,
    DropdownMenu: dropdownMenuConfig,
    Alert: alertConfig,
    AlertDialog: alertDialogConfig,
    Breadcrumb: breadcrumbConfig,
    ButtonGroup: buttonGroupConfig,
    Command: commandConfig,
    ContextMenu: contextMenuConfig,
    Drawer: drawerConfig,
    Form: formConfig,
    HoverCard: hoverCardConfig,
    InputGroup: inputGroupConfig,
    InputOtp: inputOtpConfig,
    Menubar: menubarConfig,
    Pagination: paginationConfig,
    Select: selectConfig,
    Sheet: sheetConfig,
    Table: tableConfig,
    ToggleGroup: toggleGroupConfig,
    Calendar: calendarConfig,
    NavigationMenu: navigationMenuConfig,
    Combobox: comboboxConfig,
    Resizable: resizableConfig,
    DatePicker: datePickerConfig,
    Carousel: carouselConfig,
    Sonner: sonnerConfig,
    DataTable: dataTableConfig,
    Chart: chartConfig,
    Accordion: accordionConfig,
    Dialog: dialogConfig,
    Sidebar: sidebarConfig,
  },

  playgroundGlobalCss,

  canvasSizes: {
    popover: { width: 200, height: 120 },
    tooltip: { width: 200, height: 120 },
  },
};
